name: Packer Workflow

on:
  push:
    branches: [ base ]
  workflow_dispatch:

env:
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  PKR_VAR_client_id: ${{ secrets.PKR_VAR_CLIENT_ID }}
  PKR_VAR_subscription_id: ${{ secrets.PKR_VAR_SUBSCRIPTION_ID }}
  PKR_VAR_client_secret: ${{ secrets.PKR_VAR_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.PKR_VAR_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.PKR_VAR_SUBSCRIPTION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.PKR_VAR_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_admin_username: ${{ secrets.TF_VAR_ADMIN_USERNAME }}
  TF_VAR_admin_password: ${{ secrets.TF_VAR_ADMIN_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Packer Init
        working-directory: ./packer
        run: packer init .

      - name: Packer Build
        working-directory: ./packer
        run: packer build .